# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 08:04
from __future__ import unicode_literals

import api.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('identifier', models.CharField(default=api.utils.get_account_identifier, max_length=8, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBR', 'GBR'), ('CHF', 'CHF')], default='USD', max_length=5)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='28efedeb36c3496fb52d4899a077e700', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=api.utils.get_account_identifier, max_length=8, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('Completed', 'Completed'), ('Declined', 'Declined'), ('Created', 'Created')], default='Created', max_length=10)),
                ('destAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destAccount', to='api.Account')),
                ('sourceAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceAccount', to='api.Account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
