# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CHF', 'CHF')], default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(default='86fdabad60374c04a98ffbf603aca788', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destAccount', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sourceAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourceAccount', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('completed', 'completed'), ('declined', 'declined'), ('created', 'created')], default='created', max_length=10),
        ),
    ]
