# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170819_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(default='101f935bae5c429fb0dd8f622bbbfd61', max_length=20),
        ),
    ]
