# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170820_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(default='0943464b840646c6a05aafeb21120138', max_length=20),
        ),
    ]
